[Feature][Seatunnel-core] format usage help output
apache/seatunnel pull request #1788
Opened 2022-05-04 10:02 UTC by legendtkl

## Purpose of this pull request

related issue: https://github.com/apache/incubator-seatunnel/issues/1787

With this PR, we can get a better output of usage help message

Before
```shell
./start-seatunnel-flink.sh -h
Usage: start-seatunnel-flink.sh [options] Options: -t, --check check config Default: false start-seatunnel-flink.sh start-seatunnel-spark.sh start-seatunnel-sql.sh -c, --config Config file -h, --help Show the usage message -r, --run-mode job run mode, run or run-application Default: RUN Possible Values: [RUN, APPLICATION_RUN] -i, --variable variable substitution, such as -i city=beijing, or -i date=20190318 Default: []
```

After
```shell
Usage: start-seatunnel-sql.sh [options]
  Options:
    -t, --check    check config (default: false)
  * -c, --config   Config file
    -h, --help     Show the usage message
    -r, --run-mode job run mode, run or run-application (default: RUN) 
                   (values: [RUN, APPLICATION_RUN])
    -i, --variable variable substitution, such as -i city=beijing, or -i 
                   date=20190318 (default: [])
```

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

2022-05-04 10:03 UTC, legendtkl commented
Hi, @ruanwenjun , would you help review this tiny PR when you're available?

Thanks,
Kelu.

2022-05-05 01:49 UTC, ruanwenjun commented
@legendtkl Which system are you using, Windows?

2022-05-05 02:03 UTC, legendtkl commented
macOS Monterey  @ruanwenjun

2022-05-05 02:07 UTC, ruanwenjun commented
> macOS Monterey @ruanwenjun

It looks well on my laptop(macOS x86).
<img width="967" alt="image" src="https://user-images.githubusercontent.com/22415594/166854279-6d6c413c-71a6-48ac-8585-44f60f220499.png">

2022-05-05 02:16 UTC, legendtkl commented
it's wired... This is my case.

<img width="1907" alt="image" src="https://user-images.githubusercontent.com/2370761/166854835-59df2f5f-f3fa-4f5a-b40c-dd387d8b8fb7.png">
<img width="586" alt="image" src="https://user-images.githubusercontent.com/2370761/166854847-063d970e-1d32-496f-8a10-ee2a1e884c43.png">

2022-05-05 02:29 UTC, ruanwenjun commented
> 

Sorry, you are right, I didn't update my code.

2022-05-05 02:31 UTC, ruanwenjun requested changes

2022-05-05 02:31 UTC, ruanwenjun commented on seatunnel-core/seatunnel-core-flink/src/test/java/org/apache/seatunnel/core/flink/utils/CommandLineUtilsTest.java
> +        Assert.assertTrue(flinkCommandArgs.isHelp());
This test case need to be removed, since this will close the JVM.

2022-05-05 02:57 UTC, ruanwenjun approved these changes
LGTM

2022-05-05 04:10 UTC, merged