[Feature][Doc] imporve doc about connector-v2 schema feature
apache/seatunnel pull request #3344
Opened 2022-11-09 08:43 UTC by liugddx

## Purpose of this pull request

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/incubator-seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/incubator-seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/incubator-seatunnel/blob/dev/seatunnel-dist/pom.xml)

2022-11-09 08:44 UTC, liugddx commented
@EricJoy2048 @Hisoka-X ptal

2022-11-09 08:46 UTC, Hisoka-X approved these changes, later dismissed

2022-11-09 08:47 UTC, Hisoka-X commented
@TyrantLucifer PTAL.

2022-11-09 14:17 UTC, EricJoy2048 approved these changes, later dismissed

2022-11-09 14:18 UTC, EricJoy2048 commented
@TyrantLucifer  PTAL.

2022-11-09 15:00 UTC, TyrantLucifer requested changes

2022-11-09 15:00 UTC, TyrantLucifer commented on docs/en/concept/schema-feature.md
> +| map       | A Map is an object that maps keys to values.                 |
Please add the type restriction case for array and map.

2022-11-10 01:42 UTC, TyrantLucifer requested changes

2022-11-10 01:42 UTC, TyrantLucifer commented on docs/en/concept/schema-feature.md
>  ## How to use schema
Please also add array and map examples in there.

2022-11-10 06:00 UTC, TyrantLucifer approved these changes
+1

2022-11-10 06:13 UTC, Hisoka-X approved these changes

2022-11-10 06:13 UTC, merged