[Improve][Connector-V2][TableStore] Unified excetion for TableStore sink connector
apache/seatunnel pull request #3527
Opened 2022-11-23 06:06 UTC by TaoZex

## Purpose of this pull request
https://github.com/apache/incubator-seatunnel/issues/3547
sub-task of https://github.com/apache/incubator-seatunnel/issues/2930
Unified excetion for TableStore sink connector

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/incubator-seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/incubator-seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/incubator-seatunnel/blob/dev/seatunnel-dist/pom.xml)

2022-11-24 06:44 UTC, TaoZex commented
@TyrantLucifer @wuchunfu PTAL

2022-11-24 07:35 UTC, EricJoy2048 approved these changes, later dismissed

2022-11-24 08:02 UTC, TyrantLucifer requested changes

2022-11-24 08:02 UTC, TyrantLucifer commented on seatunnel-connectors-v2/connector-tablestore/src/main/java/org/apache/seatunnel/connectors/seatunnel/tablestore/serialize/DefaultSeaTunnelRowSerializer.java
> +                throw new TablestoreConnectorException(TablestoreConnectorErrorCode.UNSUPPORTED_COLUMN_TYPE,
CommonErrorCode.UNSUPPORTED_DATA_TYPE is better, please remove this redundant error code.

2022-11-24 08:02 UTC, TyrantLucifer commented on seatunnel-connectors-v2/connector-tablestore/src/main/java/org/apache/seatunnel/connectors/seatunnel/tablestore/serialize/DefaultSeaTunnelRowSerializer.java
> +                throw new TablestoreConnectorException(TablestoreConnectorErrorCode.UNSUPPORTED_PRIMARY_KEY_TYPE,
CommonErrorCode.UNSUPPORTED_DATA_TYPE is better, please remove this redundant error code.

2022-11-24 08:02 UTC, TyrantLucifer commented on seatunnel-connectors-v2/connector-tablestore/src/main/java/org/apache/seatunnel/connectors/seatunnel/tablestore/serialize/DefaultSeaTunnelRowSerializer.java
> +                throw new TablestoreConnectorException(TablestoreConnectorErrorCode.UNSUPPORTED_COLUMN_TYPE,
CommonErrorCode.UNSUPPORTED_DATA_TYPE is better, please remove this redundant error code.

2022-11-24 08:02 UTC, TyrantLucifer commented on seatunnel-connectors-v2/connector-tablestore/src/main/java/org/apache/seatunnel/connectors/seatunnel/tablestore/serialize/DefaultSeaTunnelRowSerializer.java
> +                throw new TablestoreConnectorException(TablestoreConnectorErrorCode.UNSUPPORTED_PRIMARY_KEY_TYPE,
CommonErrorCode.UNSUPPORTED_DATA_TYPE is better, please remove this redundant error code.

2022-11-24 08:02 UTC, TyrantLucifer commented on seatunnel-connectors-v2/connector-tablestore/src/main/java/org/apache/seatunnel/connectors/seatunnel/tablestore/sink/TablestoreSinkClient.java
> +            throw new TablestoreConnectorException(TablestoreConnectorErrorCode.FLUSH_DATA_FAILED,
CommonErrorCode.FLUSH_DATA_FAILED is better, please remove this redundant error code.

2022-11-24 08:02 UTC, TyrantLucifer commented on seatunnel-connectors-v2/connector-tablestore/src/main/java/org/apache/seatunnel/connectors/seatunnel/tablestore/sink/TablestoreSinkClient.java
>              for (BatchWriteRowResponse.RowResult rowResult : response.getFailedRows()) {
Why using for here?

2022-11-24 14:27 UTC, TaoZex commented on seatunnel-connectors-v2/connector-tablestore/src/main/java/org/apache/seatunnel/connectors/seatunnel/tablestore/serialize/DefaultSeaTunnelRowSerializer.java
> +                throw new TablestoreConnectorException(TablestoreConnectorErrorCode.UNSUPPORTED_COLUMN_TYPE,
Thank you for your advice. It helped me a lot. I have fixed it.

2022-11-26 09:15 UTC, TyrantLucifer approved these changes

2022-11-26 09:22 UTC, Hisoka-X approved these changes

2022-11-26 09:22 UTC, merged