[Feature][Connector V2] Add GoogleSheets Sink
apache/seatunnel pull request #3848
Opened 2023-01-02 11:42 UTC by TaoZex

## Purpose of this pull request

Add GoogleSheets Sink

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/incubator-seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/incubator-seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/incubator-seatunnel/blob/dev/seatunnel-dist/pom.xml)

2023-01-02 11:47 UTC, TaoZex commented
I don't have permission to update this pr:https://github.com/apache/incubator-seatunnel/pull/3411
So I created this pr to improve it. @EricJoy2048

2023-01-03 01:25 UTC, CalvinKirs requested changes
Please provide UT or IT to verify this, you can set to disable, but we should have a test code that can be quickly and easily configured and then run.

2023-01-03 05:32 UTC, TaoZex commented
> Please provide UT or IT to verify this, you can set to disable, but we should have a test code that can be quickly and easily configured and then run.

Thanks for your advice. I will add e2e test code.

2023-01-06 07:20 UTC, TaoZex commented
@Hisoka-X @EricJoy2048 PTAL

2023-01-17 10:27 UTC, TaoZex commented
@hailin0 @Hisoka-X @EricJoy2048 PTAL

2023-01-31 11:38 UTC, EricJoy2048 commented on docs/en/connector-v2/sink/GoogleSheets.md
> +- [ ] [schema projection](../../concept/connector-v2-features.md)
`schema projection` is not sink key features. Please reference https://seatunnel.apache.org/docs/concept/connector-v2-features.

2023-01-31 11:38 UTC, EricJoy2048 commented on seatunnel-connectors-v2/connector-google-sheets/src/main/java/org/apache/seatunnel/connectors/seatunnel/google/sheets/sink/SheetsSinkWriter.java
> +        // not need close
Need `flush()` ?

2023-02-08 15:27 UTC, TaoZex commented on seatunnel-connectors-v2/connector-google-sheets/src/main/java/org/apache/seatunnel/connectors/seatunnel/google/sheets/sink/SheetsSinkWriter.java
> +        // not need close
Thanks. I have fixed it.

2023-02-14 07:03 UTC, TaoZex commented
@EricJoy2048 I have resolved conflict. PTAL.

2023-02-27 14:56 UTC, TyrantLucifer requested changes
Update release-note plugin_config seatunne-dist

2023-02-27 14:56 UTC, TyrantLucifer commented on docs/en/connector-v2/sink/GoogleSheets.md
> +  ## Description
remove blank

2023-02-27 14:56 UTC, TyrantLucifer commented on seatunnel-connectors-v2/connector-google-sheets/src/main/java/org/apache/seatunnel/connectors/seatunnel/google/sheets/config/SheetsParameters.java
> +        NetHttpTransport httpTransport = null;
```suggestion
        NetHttpTransport httpTransport;
```

2023-02-27 14:56 UTC, TyrantLucifer commented on seatunnel-connectors-v2/connector-google-sheets/src/main/java/org/apache/seatunnel/connectors/seatunnel/google/sheets/exception/GoogleSheetsConnectorErrorCode.java
> +    public String getErrorMessage() {
Remove

2023-02-27 14:58 UTC, TyrantLucifer commented
Offser the snapshot images of this connectors in different engines (flink spark zeta), not the snapshot images of seatunnel-examples, you need compile it and run test cases in integration test env.

2023-05-19 06:52 UTC, hailin0 commented
waitting ci

2023-05-22 04:05 UTC, hailin0 commented
LGTM

2023-05-22 04:06 UTC, hailin0 approved these changes

2023-05-22 04:17 UTC, TyrantLucifer requested changes
Please offer test screenshots.

2023-05-22 04:17 UTC, TyrantLucifer commented on seatunnel-e2e/seatunnel-connector-v2-e2e/connector-googlesheets-e2e/src/test/resources/fakesource_to_googlesheets.conf
> +        age = "int"
test all data types

2023-07-27 03:54 UTC, TyrantLucifer commented
Any process this pull request?

2023-07-31 02:53 UTC, closed without merging