[Bug] [seatunnel-connectors] [seatunnel-connector-spark-clickhouse] Data cannot be imported to all nodes by configuring split_mode and sharding_key
apache/seatunnel pull request #4772
Opened 2023-05-17 10:57 UTC by wuxizhi777

## Purpose of this pull request
https://github.com/apache/incubator-seatunnel/issues/4770

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/incubator-seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/incubator-seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/incubator-seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/incubator-seatunnel/blob/dev/release-note.md).

2023-06-06 06:36 UTC, zhilinli123 approved these changes

2023-06-06 06:37 UTC, zhilinli123 commented
PTAL : @Hisoka-X

2023-06-06 06:42 UTC, Hisoka-X commented
Good catch! Can you add UT for `getShard` method? Thanks

2023-06-06 06:50 UTC, zhilinli123 commented
> Good catch! Can you add UT for `getShard` method? Thanks

<img width="1033" alt="image" src="https://github.com/apache/seatunnel/assets/76689593/18fb6751-7399-4c15-b990-6a10a63dca18">
It's not a negative number, right?

2023-06-06 06:55 UTC, Hisoka-X commented
> It's not a negative number, right? @Hisoka-X

@zhilinli123 It can't be negative. I suggest compare two result of change before and change after.

2023-06-06 07:12 UTC, zhilinli123 commented
> > It's not a negative number, right? @Hisoka-X
> 
> @zhilinli123 It can't be negative. I suggest compare two result of change before and change after.

   ```
@Test
    public void testHashValue() {
        String a = "a,b,c,d,e,f";
        for (Object o : Arrays.stream(a.split(",")).toArray()) {
            System.out.println(getShard(o));
        }
    }
    public int getShard(Object shardValue) {
        int offset =
                (int)
                        (HASH_INSTANCE.hash(
                                ByteBuffer.wrap(
                                        shardValue
                                                .toString()
                                                .getBytes(StandardCharsets.UTF_8)),
                                0)
                                        & Long.MAX_VALUE % 6);
        return offset;
    }

```
```
//  Before            After
//  1                   -5
//  1                   3
//  1                   -5
//  0                   2
//  0                   4
//  1                   -3
```

2023-06-06 14:22 UTC, zhilinli123 commented
> > It's not a negative number, right? @Hisoka-X
> 
> @zhilinli123 It can't be negative. I suggest compare two result of change before and change after.

```
    public static void main(String[] args) {
        // Create an instance of the XXHash64 algorithm
        XXHashFactory factory = XXHashFactory.fastestInstance();
        XXHash64 hash64 = factory.hash64();

        // Define your input data
        byte[] input ;
        String a = "a,b,c,d,e,f";
        for (String inputs : a.split(",")) {
            input = inputs.getBytes();
            // Calculate the hash value
            long hashValue = hash64.hash(input, 0, input.length, 0);

            // Apply modulo operation to get a non-negative result
            int modulo = 6;
            long nonNegativeResult = (hashValue & Long.MAX_VALUE) % modulo;

            // Print the non-negative result
            System.out.println("Non-negative result: " + nonNegativeResult);

        }
    }
```
**Console:**
```
Non-negative result: 3
Non-negative result: 3
Non-negative result: 3
Non-negative result: 2
Non-negative result: 4
Non-negative result: 5

```
I have written a simple test demo about this problem, please help to see if it meets the expectations
@Hisoka-X

2023-06-07 02:20 UTC, Hisoka-X commented
@zhilinli123 Any reason for negative result?

2023-06-07 06:38 UTC, Carl-Zhou-CN commented
@Hisoka-X ,@zhilinli123 I think it's probably a long strong int, which makes it a negative number

2023-06-07 08:18 UTC, zhilinli123 commented
> @Hisoka-X ,@zhilinli123 My guess is that it may be due to the conversion of a long to an int, which resulted in a negative number.

  I put the results of the execution on top

2023-06-07 09:01 UTC, Carl-Zhou-CN commented
> > @Hisoka-X ,@zhilinli123 My guess is that it may be due to the conversion of a long to an int, which resulted in a negative number.
> 
> I put the results of the execution on top

I am just explaining the reason for the appearance of negative numbers.

2023-06-07 09:05 UTC, Carl-Zhou-CN commented
I think
        int offset =
                (int)
                        (HASH_INSTANCE.hash(
                                ByteBuffer.wrap(
                                        shardValue
                                                .toString()
                                                .getBytes(StandardCharsets.UTF_8)),
                                0)
                                & Integer.MAX_VALUE) % 6 ;

2023-06-08 03:06 UTC, wuxizhi777 commented
public class test {
    private static final XXHash64 HASH_INSTANCE = XXHashFactory.fastestInstance().hash64();
    public   int getShard(Object shardValue){
        int shardWeightCount = 6;
        int offset =
                (int)
                        ((HASH_INSTANCE.hash(
                                ByteBuffer.wrap(
                                        shardValue
                                                .toString()
                                                .getBytes(StandardCharsets.UTF_8)),
                                0)
                                & Long.MAX_VALUE)
                                % shardWeightCount);
        return  offset;
    }

    @Test
    public  void testShared(){
        String a = "a,b,c,d,e,f";
        for(Object o: Arrays.stream(a.split(",")).toArray()){
            System.out.println(getShard(o));
        }

    }


}
===================
the result is :
3
3
3
2
4
5

2023-06-08 03:23 UTC, Carl-Zhou-CN commented
@wuxizhi777 You're right. Can you help add this test case to this pull request?

2023-06-08 03:58 UTC, TyrantLucifer requested changes
Thank you for your contribution. Please add unit test.

2023-06-10 11:34 UTC, TyrantLucifer commented
@Hisoka-X PTAL.

2023-06-12 08:37 UTC, Hisoka-X commented on seatunnel-connectors-v2/connector-clickhouse/src/test/java/org/apache/seatunnel/connectors/seatunnel/clickhouse/ClickhouseFactoryTest.java
> +            System.out.println(getShard(o));
Please use `Assertions` to make sure to result are right. Also please provide the test case to make sure to all shard can be selected. Tips: maybe we can use 10000 keys with random string to invoke `getShard` then get each shard index count which return by `getShard`. I believe when the number of keys more large, the shard index will be more balanced.

2023-06-12 15:32 UTC, zhilinli123 commented on seatunnel-connectors-v2/connector-clickhouse/src/test/java/org/apache/seatunnel/connectors/seatunnel/clickhouse/ClickhouseFactoryTest.java
> +            System.out.println(getShard(o));
> Please use `Assertions` to make sure to result are right. Also please provide the test case to make sure to all shard can be selected. Tips: maybe we can use 10000 keys with random string to invoke `getShard` then get each shard index count which return by `getShard`. I believe when the number of keys more large, the shard index will be more balanced.
```
public static void main(String[] args) {
        // Create an instance of the XXHash64 algorithm
        XXHashFactory factory = XXHashFactory.fastestInstance();
        XXHash64 hash64 = factory.hash64();

        // Define your input data
        byte[] input;
        ArrayList<String> strings = new ArrayList<>();

        Map<Long, Long> resultCount = new HashMap<>();
        for (int i = 1; i <= 100000; i++) {
            input = UUID.randomUUID().toString().getBytes();
            // Calculate the hash value
            long hashValue = hash64.hash(input, 0, input.length, 0);

            // Apply modulo operation to get a non-negative result
            int modulo = 6;
            long nonNegativeResult = (hashValue & Long.MAX_VALUE) % modulo;
            Long keyValue = resultCount.get(nonNegativeResult);  // 获取当前键值对应的值

            if (keyValue != null) {
                resultCount.put(nonNegativeResult, keyValue + 1L);

            } else {
                resultCount.put(nonNegativeResult, 1L);
            }

            // Print the non-negative result
//            System.out.println("Non-negative result: " + nonNegativeResult);

        }
        Long totalResult = 0L;
        for (Long key : resultCount.keySet()) {
            System.out.println("Key:"+key+" count:"+resultCount.get(key));
            totalResult+=resultCount.get(key);
        }
        System.out.println("Sum:"+totalResult);

        
//        Console Result:
//        Key:0 count:16651
//        Key:1 count:16595
//        Key:2 count:16648
//        Key:3 count:16650
//        Key:4 count:16946
//        Key:5 count:16510
//        Sum:100000

    }
```
Looks good, PTAL

2023-06-13 08:15 UTC, Hisoka-X commented on seatunnel-connectors-v2/connector-clickhouse/src/test/java/org/apache/seatunnel/connectors/seatunnel/clickhouse/ClickhouseFactoryTest.java
> +            System.out.println(getShard(o));
Great, please add this part test code to branch. Also remember, `Please use Assertions`

2023-06-13 08:58 UTC, zhilinli123 commented on seatunnel-connectors-v2/connector-clickhouse/src/test/java/org/apache/seatunnel/connectors/seatunnel/clickhouse/ClickhouseFactoryTest.java
> +            System.out.println(getShard(o));
> Great, please add this part test code to branch. Also remember, `Please use Assertions`

CC @wuxizhi777

2023-06-13 14:39 UTC, wuxizhi777 commented on seatunnel-connectors-v2/connector-clickhouse/src/test/java/org/apache/seatunnel/connectors/seatunnel/clickhouse/ClickhouseFactoryTest.java
> +            System.out.println(getShard(o));
ok,   boss, I  hown

2023-06-14 12:33 UTC, 1309637127 commented
This cause 2 problems:
1、Seatunnel push data to only part of the nodes
We have 6 nodes in the product environment and only 4 nodes have data, the other have no data.
2、We expect the xxHash have the same xxHash result as Clickhouse
We have further ETL job in Clickhouse, we use cust_no as the sharding key, we expect all the data concerning with the same cust_no stay in the same node, but we've test the xxHash result with Clickhouse result they are not equal.

Below is the java xxHash and Clickhouse xxHash result "00000186620663":
java xxHash: -1055457840867779448
java xxHash & Long.MAX result: 8167914195986996360
Clickhouse xxHash: 17391286232841772168

And with the xxHash result seatunnel push the customer to shard0 and in clickhouse put the customer is in shard 5

2023-08-07 03:10 UTC, zhilinli123 commented
PTAL: @Hisoka-X

2023-10-25 10:01 UTC, hailin0 commented on .idea/vcs.xml
> -<?xml version="1.0" encoding="UTF-8"?>
revert this file

2024-06-15 02:27 UTC, Hisoka-X commented on seatunnel-connectors-v2/connector-clickhouse/src/test/java/org/apache/seatunnel/connectors/seatunnel/clickhouse/ClickhouseFactoryTest.java
> +    public void testShared() {
The test case look weird, it only prove the logic of `(hashValue & Long.MAX_VALUE) % modulo` are right. But can not make sure the `getShard` method return right result. I think the test case should test `getShard` method.

2025-07-22 00:39 UTC, closed without merging