[Bugfix][zeta] Local tasks are not allowed to run concurrently; only one can be running at a time.
apache/seatunnel pull request #4996
Opened 2023-06-29 07:05 UTC by hanyouyou13

## Purpose of this pull request
fix https://github.com/apache/seatunnel/issues/4986

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

2023-06-29 14:36 UTC, TyrantLucifer requested changes
![image](https://github.com/apache/seatunnel/assets/51053924/9803e0be-5bd9-4308-a8c5-aeef5efc9066)

Please fix ci error

2023-07-02 15:04 UTC, hanyouyou13 commented
ci test ClusterFaultToleranceTwoPipelineIT.testTwoPipelineBatchJobRestoreIn2NodeMasterDown, I see after the master shutdown, the JobStatus will become FAILED.

2023-07-03 08:06 UTC, Hisoka-X reviewed
Can you add new test case with create two local job to prevent this feature from being broken by other code change?

2023-07-13 06:00 UTC, Hisoka-X commented on seatunnel-e2e/seatunnel-engine-e2e/connector-seatunnel-e2e-base/src/test/java/org/apache/seatunnel/engine/e2e/LocalIT.java
> +    public void testSubmitTwoIndependentJobByLocalSever()
Please use docker to create test case just like e2e in https://github.com/apache/seatunnel/tree/dev/seatunnel-e2e. You create two job in same instance, I think it can't prove the local tasks can run more than one job in the same time.

Only create two JVM instance to run two job can make sure the feature are right.

2023-07-13 06:00 UTC, Hisoka-X commented on seatunnel-core/seatunnel-starter/src/main/java/org/apache/seatunnel/core/starter/seatunnel/command/ClientExecuteCommand.java
> +                networkConfig.setAddresses(Lists.newArrayList(connectAddress));
This way only work on two job running on same JVM, is my thinking correct?

2023-07-18 00:32 UTC, hanyouyou13 commented on seatunnel-core/seatunnel-starter/src/main/java/org/apache/seatunnel/core/starter/seatunnel/command/ClientExecuteCommand.java
> +                networkConfig.setAddresses(Lists.newArrayList(connectAddress));
Thank you for your suggestion. This test case expresses each local task runs on a different zeta server.

2023-08-05 09:19 UTC, ic4y commented
> Currently, we can run multiple tasks in local mode using separate JVM instances. The issue likely stems from the hazelcast-client.yaml where cluster-members doesn't include multiple ports. I suggest configuring it like the image shown below:
> <img alt="image" width="240" src="https://user-images.githubusercontent.com/83933160/258575480-746bf90b-5fbb-4c23-afc4-177c15063c65.png">
> With this, we can run up to 9 jobs simultaneously

@hanyouyou13 @Hisoka-X So, this PR is not necessary.

2023-08-08 00:34 UTC, hanyouyou13 commented
> @hanyouyou13 @Hisoka-X So, this PR is not necessary.

2023-08-08 00:34 UTC, closed without merging

2023-08-08 00:51 UTC, hanyouyou13 commented
> > Currently, we can run multiple tasks in local mode using separate JVM instances. The issue likely stems from the hazelcast-client.yaml where cluster-members doesn't include multiple ports. I suggest configuring it like the image shown below:
> > <img alt="image" width="240" src="https://user-images.githubusercontent.com/83933160/258575480-746bf90b-5fbb-4c23-afc4-177c15063c65.png">
> > With this, we can run up to 9 jobs simultaneously
> 
> @hanyouyou13 @Hisoka-X So, this PR is not necessary.

Currently, if we can run multiple tasks in local mode using separate JVM instances, The server and clinet of hazelcast must be modified to uniquely match each port at the same time.
This pr solves run local task using the same jvm to start the hazelcast server.

2023-08-08 02:48 UTC, ic4y commented
> > > Currently, we can run multiple tasks in local mode using separate JVM instances. The issue likely stems from the hazelcast-client.yaml where cluster-members doesn't include multiple ports. I suggest configuring it like the image shown below:
> > > <img alt="image" width="240" src="https://user-images.githubusercontent.com/83933160/258575480-746bf90b-5fbb-4c23-afc4-177c15063c65.png">
> > > With this, we can run up to 9 jobs simultaneously
> > 
> > 
> > @hanyouyou13 @Hisoka-X So, this PR is not necessary.
> 
> Currently, if we can run multiple tasks in local mode using separate JVM instances, The server and clinet of hazelcast must be modified to uniquely match each port at the same time. This pr solves run local task using the same jvm to start the hazelcast server.

Thank you for your effort and contribution, @hanyouyou13. Although we're not merging this PR right now, your dedication is truly appreciated. We hope you'll continue to contribute in the future. Your input is valuable to us!