Redis select db
apache/seatunnel pull request #5570
Opened 2023-09-27 05:07 UTC by xiaofan2022

### Purpose of this pull request
redis select_db index
### Does this PR introduce _any_ user-facing change?
no
### How was this patch tested?

### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [x] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

2023-10-04 06:33 UTC, TyrantLucifer requested changes
Thank you for your contribution, overall LGTM, but you need offer e2e test cases for this change to verify it worked.

2023-10-04 06:33 UTC, TyrantLucifer commented on docs/en/connector-v2/sink/Redis.md
> +| db_num         | int    | no                    | -             |
```suggestion
| db_num         | int    | no                    | 0            |
```

2023-10-04 06:33 UTC, TyrantLucifer commented on seatunnel-connectors-v2/connector-redis/src/main/java/org/apache/seatunnel/connectors/seatunnel/redis/config/RedisParameters.java
> +    private Integer dbNum;
```suggestion
    private int dbNum;
```

2023-10-04 06:33 UTC, TyrantLucifer commented on seatunnel-connectors-v2/connector-redis/src/main/java/org/apache/seatunnel/connectors/seatunnel/redis/config/RedisParameters.java
> +                }
```suggestion
                    jedis.select(dbNum);
```

2023-10-04 06:33 UTC, TyrantLucifer commented on seatunnel-connectors-v2/connector-redis/src/main/java/org/apache/seatunnel/connectors/seatunnel/redis/config/RedisParameters.java
> +                    jedisWrapper.select(dbNum);
The same as above.

2023-10-07 07:44 UTC, xiaofan2022 reviewed
done

2023-10-07 07:44 UTC, xiaofan2022 commented on seatunnel-connectors-v2/connector-redis/src/main/java/org/apache/seatunnel/connectors/seatunnel/redis/config/RedisParameters.java
> +                }
done

2023-10-07 07:44 UTC, xiaofan2022 commented on seatunnel-connectors-v2/connector-redis/src/main/java/org/apache/seatunnel/connectors/seatunnel/redis/config/RedisParameters.java
> +    private Integer dbNum;
done

2023-10-07 09:23 UTC, hailin0 commented
update PR title ?

2023-10-08 01:50 UTC, xiaofan2022 reviewed
done

2023-10-08 09:41 UTC, xiaofan2022 reviewed
done

2023-10-11 08:22 UTC, Hisoka-X commented on seatunnel-connectors-v2/connector-redis/src/main/java/org/apache/seatunnel/connectors/seatunnel/redis/config/RedisConfig.java
> +                            "redis  database index id, It is connected to db 0 by default");
```suggestion
                            "Redis database index id, it is connected to db 0 by default");
```

2023-10-13 04:41 UTC, xiaofan2022 commented on seatunnel-connectors-v2/connector-redis/src/main/java/org/apache/seatunnel/connectors/seatunnel/redis/config/RedisConfig.java
> +                            "redis  database index id, It is connected to db 0 by default");
done

2023-10-13 06:06 UTC, Hisoka-X approved these changes
LGTM, but I think @TyrantLucifer should take a look.

2023-10-17 06:52 UTC, xiaofan2022 commented
> Thank you for your contribution, overall LGTM, but you need offer e2e test cases for this change to verify it worked.

done

2023-10-17 07:00 UTC, hailin0 approved these changes

2023-10-17 07:10 UTC, TyrantLucifer approved these changes

2023-10-17 07:10 UTC, merged

2023-10-17 07:12 UTC, Hisoka-X commented
Thanks @xiaofan2022 and @hailin0 @TyrantLucifer for review.