[feature][Transform] Transform supports multi-table scenarios
apache/seatunnel pull request #5646
Opened 2023-10-17 09:28 UTC by ic4y

### Purpose of this pull request

### Does this PR introduce _any_ user-facing change?

### How was this patch tested?

### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

2023-10-25 03:45 UTC, hailin0 commented
check ci error

2023-12-01 09:01 UTC, Hisoka-X requested changes

2023-12-01 09:01 UTC, Hisoka-X commented on seatunnel-transforms-v2/src/main/java/org/apache/seatunnel/transform/common/AbstractMultiCatalogSupportTransform.java
> +                        .collect(Collectors.toList());
This processing method contains serious potential problems. If there are 10 tables in the upstream, but only one of the tables is need be transformed, the job will report an error because the transform of the remaining 9 tables cannot be constructed normally, there is no corresponding configuration, and it stands to reason that the transforms of the remaining 9 tables should not be constructed, because no modifications have been made at all. We should not foreach the upstream catalogtables, but foreach the user's transform configuration.

2024-07-21 07:01 UTC, cobolbaby commented
Can transform-v2 improve this feature? Certain tables need to be transformed during multi-table CDC synchronization.

@EricJoy2048 @ic4y

2024-12-21 07:24 UTC, hailin0 commented
completed for https://github.com/apache/seatunnel/pull/7628

2024-12-21 07:24 UTC, closed without merging