File option
apache/seatunnel pull request #5680
Opened 2023-10-20 23:50 UTC by liunaijie

### Purpose of this pull request

close #5461 and #4572 
1. unified option in file source/sink (source parameter delimiter update to field_delimiter)
2. update the doucment
 a) update parameter name
 b) refactor docs using unified format

### Does this PR introduce _any_ user-facing change?

### How was this patch tested?

use e2e 

### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  4. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  5. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

2023-10-21 03:55 UTC, Hisoka-X commented
So after this PR, seem like `delimiter` will not worked. This is unacceptable and will hinder users who need to upgrade. If we need to modify a configuration key, we should be compatible with the old configuration at the same time.

2023-10-21 03:56 UTC, Hisoka-X commented
So I think you should answer this question.
![image](https://github.com/apache/seatunnel/assets/32387433/5d9625c6-9117-41e5-b7e3-f3b245494d78)

2023-10-23 06:51 UTC, EricJoy2048 requested changes

2023-10-23 06:51 UTC, EricJoy2048 commented on seatunnel-connectors-v2/connector-file/connector-file-base/src/main/java/org/apache/seatunnel/connectors/seatunnel/file/config/BaseSourceConfig.java
> +    public static final Option<String> FIELD_DELIMITER =
Directly modifying parameter names can cause compatibility issues.
You can update option like this:
```
    public static final Option<String> FIELD_DELIMITER =
            Options.key("field_delimiter")
                    .stringType()
                    .defaultValue(TextFormatConstant.SEPARATOR[0])
                    .withFallbackKeys("delimiter")
                    .withDescription(
                            "The separator between columns in a row of data. Only needed by `text` file format");


```

And then you need update the code at the point used this option.

```
String delimiter =
                        ReadonlyConfig.fromConfig(pluginConfig)
                                .get(BaseSourceConfig.FIELD_DELIMITER);
```

2023-10-27 06:17 UTC, Hisoka-X reviewed
Could you add a test case for old config key `delimiter`? We should make sure the `delimiter` work fine too after this change.

2023-10-27 07:08 UTC, Hisoka-X commented on docs/en/connector-v2/source/FtpFile.md
> +**delimiter** parameter will deprecate after version 2.3.5, please use **field_delimiter** instead.
```suggestion
**delimiter** parameter will deprecate after version 2.3.4, please use **field_delimiter** instead.
```

2023-10-27 07:08 UTC, Hisoka-X commented on docs/en/connector-v2/source/HdfsFile.md
> +**delimiter** parameter will deprecate after version 2.3.5, please use **field_delimiter** instead.
```suggestion
**delimiter** parameter will deprecate after version 2.3.4, please use **field_delimiter** instead.
```

2023-10-27 07:08 UTC, Hisoka-X commented on seatunnel-e2e/seatunnel-connector-v2-e2e/connector-file-local-e2e/src/test/resources/excel/local_excel_projection_to_assert_with_delimiter.conf
> +  }
The test case seem like can not prove the delimiter is ":". Could you add a rule to check row value? You can refer https://github.com/apache/seatunnel/pull/5083/files#diff-a68b2797462655fd5ee139c5c129df223f4de9c25e72e41a6432012d00ede0a8

2023-10-30 07:20 UTC, Hisoka-X approved these changes

2023-10-30 07:20 UTC, Hisoka-X commented
Thanks @liunaijie .Waiting CI pass.

2023-10-30 15:15 UTC, EricJoy2048 approved these changes

2023-10-30 15:15 UTC, merged