[Doc][Improve]Add Support Chinese for start-v2/locally/quick-start-flink.md and start-v2/locally/quick-start-spark.md
apache/seatunnel pull request #6412
Opened 2024-02-29 00:45 UTC by dzygoon

Add Support Chinese for start-v2/locally/quick-start-flink.md and start-v2/locally/quick-start-spark.md

2024-03-10 12:08 UTC, davidzollo requested changes
Hi dzygoon, you did good job, please check and update some places.

2024-03-10 12:08 UTC, davidzollo commented on docs/zh/start-v2/locally/quick-start-flink.md
> +在开始前，请确保您已经按照[部署](../../../en/start-v2/locally/deployment.md)中的描述下载并部署了SeaTunnel
is `../../../en/start-v2/locally/deployment.md` should be `deployment.md`?

2024-03-10 12:08 UTC, davidzollo commented on docs/zh/start-v2/locally/quick-start-flink.md
> +flink版本`1.12.x`到`1.14.x`
Please use `Flink` instead of `flink`

2024-03-10 12:08 UTC, davidzollo commented on docs/zh/start-v2/locally/quick-start-spark.md
> +spark 2.4.x
use Spark instead

2024-03-12 06:14 UTC, dzygoon commented
> Hi dzygoon, you did good job, please check and update some places.



> Hi dzygoon, you did good job, please check and update some places.

done.

2024-04-07 12:34 UTC, EricJoy2048 approved these changes

2024-04-07 14:24 UTC, davidzollo approved these changes

2024-04-07 14:25 UTC, merged

2024-04-07 14:26 UTC, davidzollo commented
Hi @dzygoon, Sorry for the late response, I approved the changes. 
Thanks