[Feature][Flink] Support multiple tables read and write
apache/seatunnel pull request #7671
Opened 2024-09-17 03:45 UTC by PeppaPage

### Purpose of this pull request

### Does this PR introduce _any_ user-facing change?

### How was this patch tested?

### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  2. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
  3. Add ci label in [label-scope-conf](https://github.com/apache/seatunnel/blob/dev/.github/workflows/labeler/label-scope-conf.yml)
  4. Add e2e testcase in [seatunnel-e2e](https://github.com/apache/seatunnel/tree/dev/seatunnel-e2e/seatunnel-connector-v2-e2e/)
  5. Update connector [plugin_config](https://github.com/apache/seatunnel/blob/dev/config/plugin_config)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

2024-09-18 02:37 UTC, Hisoka-X commented
Please follow the guide to open ci on your fork repository. https://github.com/apache/seatunnel/runs/25166667347

2024-09-18 08:29 UTC, litiliu requested changes

2024-09-18 08:29 UTC, litiliu commented on seatunnel-translation/seatunnel-translation-flink/seatunnel-translation-flink-common/src/main/java/org/apache/seatunnel/translation/flink/sink/FlinkSink.java
> +        if (checkForCommitter())
there should be a `{` behind the if clause, it make reading easyier.

2024-09-18 08:29 UTC, litiliu commented on seatunnel-core/seatunnel-flink-starter/seatunnel-flink-13-starter/src/main/java/org/apache/seatunnel/core/starter/flink/execution/SinkExecuteProcessor.java
> +    public String extractTableIdName(TableIdentifier tableIdentifier) {
is it better to add ut to cover this logic?

2024-09-18 08:29 UTC, litiliu commented on seatunnel-core/seatunnel-flink-starter/seatunnel-flink-starter-common/src/main/java/org/apache/seatunnel/core/starter/flink/execution/SinkExecuteProcessor.java
> +    }
duplicate with the method in the seatunnel-core/seatunnel-flink-starter/seatunnel-flink-13-starter/src/main/java/org/apache/seatunnel/core/starter/flink/execution/SinkExecuteProcessor.java ?

2024-09-18 14:13 UTC, hailin0 commented on seatunnel-e2e/seatunnel-connector-v2-e2e/connector-elasticsearch-e2e/src/test/java/org/apache/seatunnel/e2e/connector/elasticsearch/ElasticsearchIT.java
>      @DisabledOnContainer(
Please delete this annotation

2024-09-19 03:26 UTC, Hisoka-X commented
cc @TyrantLucifer

2024-09-19 05:07 UTC, closed without merging